[General]
output-scalar-file-append = false 

#**.ue[*].mobility.initFromDisplayString = false
 
# Network configuration 
network = simulations.NetworkSlicing
sim-time-limit = 10s 
warmup-period = 1s 
seed-set = ${repetition} 
 
# Statistics 
output-scalar-file = ${resultdir}/${configname}/${repetition}.sca 
output-vector-file = ${resultdir}/${configname}/${repetition}.vec 
**.routingTableRecorder.enabled = false
  
*.configurator.assignAddresses = true

*.configurator.addStaticRoutes = true

# General parameters 
**.amcType = "NRAmc" 
**.targetBler = 0.01 
**.blerShift = 5   
*.configurator.config = xmldoc("./demo.xml") 


# connect the UE's NIC (NR side) to the corresponding serving gNB 
*.ue[*].macCellId = 0 
*.ue[*].masterId = 0 
*.ue[*].nrMacCellId = 1 
*.ue[*].nrMasterId = 1 
 
# Application Setup 
*.ue[*].numApps = 1 
*.server.numApps = 1 
 
*.ue[*].app[*].typename = "CbrReceiver" 
*.ue[*].app[*].localPort = 1000 
 
*.server.app[*].typename = "CbrSender"   
*.server.app[*].PacketSize = 1000      # send 800 Kb/s 
*.server.app[*].sampling_time = 0.01s 
*.server.app[*].destAddress = "ue["+string(ancestorIndex(0))+"]" # obtain the address of the client by reading its index in the array of Apps 
*.server.app[*].destPort = 1000  
*.server.app[*].localPort = 3088+ancestorIndex(0)  
*.server.app[*].startTime = uniform(0.01s,0.05s) 

# ????? ???? ??????? ???? ????? ???? ?????????? (????? 1000x1000 ???)
*.ue[*].mobility.constraintAreaMinX = 0m
*.ue[*].mobility.constraintAreaMaxX = 2000m
*.ue[*].mobility.constraintAreaMinY = 0m
*.ue[*].mobility.constraintAreaMaxY = 2000m
*.ue[*].mobility.constraintAreaMinZ = 0m
*.ue[*].mobility.constraintAreaMaxZ = 0m # ?????? 0 ????? ?????? ?? ????? ???

[Config Single-UE]
*.numUe = 1 

*.ue[*].mobility.typename = "StationaryMobility"

*.ue[*].mobility.initialX = uniform(0m, 1000m)
*.ue[*].mobility.initialY = uniform(0m, 1000m)
*.ue[*].mobility.initialZ = 0m




[Config Mobility]
*.numUe = 2 
# ????? ??? ???? ???????
**.ue[*].mobility.typename = "RandomWaypointMobility"


**.ue[*].mobility.initialX = uniform(0m, 1000m)
**.ue[*].mobility.initialY = uniform(0m, 1000m)


# ??????? ?????? ??????
*.ue[*].mobility.speed = uniform(1mps, 10mps) 















